#!/usr/bin/env bash

## Script for toggling Hyprland animations

# Vars
DIR="$HOME/.config/hypr"
STATE_FILE="$DIR/theme/.animations_state"
if [[ ! -f "$STATE_FILE" ]]; then
    echo "on" > "$STATE_FILE"
fi

# Toggle animations
toggle_animations() {
	if [[ $(cat "$STATE_FILE") == "on" ]]; then
		hyprctl --batch "keyword animations:enabled false; keyword animation fadeLayers,0; keyword animation fadeLayersIn,0; keyword animation fadeLayersOut,0"
		echo "off" > "$STATE_FILE"
	else
		hyprctl --batch "keyword animations:enabled true; keyword animation fadeLayers,1,8,default; keyword animation fadeLayersIn,1,8,default; keyword animation fadeLayersOut,1,8,default"
		echo "on" > "$STATE_FILE"
	fi
}

# Show info (format: text\ntooltip\nclass)
show_info() {
	if [[ $(cat "$STATE_FILE") == "on" ]]; then
		echo -e "󰳑\nAnimations ON\non"
	else
		echo -e "󰳒\nAnimations OFF\noff"
	fi
}

# Main
if [[ "$1" == "--toggle" ]]; then
	toggle_animations
else
	show_info
fi
