#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs ---------------------------------------

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Apply default theme (sets wallpaper and colors)
~/.config/hypr/theme/theme.sh --default &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Start network manager applet
nm-applet --indicator &

# Start mpd
exec mpd &
